#!/usr/bin/env python3
"""
export_mission.py

Converts the platform-agnostic flight_plan.json (produced by
generate_flight_plan.py) into drone/GCS-specific mission files. Produces
ONE FILE PER CHARGE CYCLE, since ground control software (ArduPilot Mission
Planner, QGroundControl, DJI Pilot) loads and flies one mission file at a
time -- the operator (or a docking/refill station) loads the next cycle's
file after the physical battery-swap / tank-refill step.

SUPPORTED FORMATS
-----------------
  ardupilot    -- QGC WPL 120 plain-text waypoint file (.waypoints), for
                   ArduPilot / Mission Planner
  px4          -- QGroundControl .plan JSON, for PX4
  generic_csv  -- simple lat/lon/alt/action CSV for debugging, spreadsheet
                   review, or feeding into your own visualization -- NOT
                   tied to any specific consumer app's mission format

DJI WPML (.kmz) -- IMPLEMENTED, WITH ONE VERIFIED GAP
-------------------------------------------------------
The file structure, KMZ packaging, mission config, waypoint/path
definition, and action-group mechanics below follow DJI's published WPML
spec exactly (github.com/dji-sdk/Cloud-API-Doc), cross-checked against a
real sample waylines.wpml from that repo. That part is solid.

HOWEVER: DJI's *public* WPML documentation only covers camera/gimbal
actions (takePhoto, gimbalRotate, rotateYaw, hover, etc.) for M30/M300/
Mavic-class drones. There is no publicly documented action tag for Agras
spray control -- Agras missions are normally generated by DJI's own Agras
planning software, and its spray-actuator schema isn't published in the
same repo. Rather than invent a plausible-sounding tag name and present it
as fact, the spray action tag/param names below are CLI-configurable
placeholders (--spray-action-tag, --spray-param-tag), clearly marked in
the generated XML with a comment, defaulting to a best-guess name. Before
trusting this for a real Agras flight: unzip a real mission exported from
DJI Pilot 2 / DJI Agras planning software, find the actual actionActuatorFunc
tag it uses for nozzle on/off, and pass it via --spray-action-tag /
--spray-param-tag to replace the placeholder.

Similarly, --drone-enum-value / --drone-sub-enum-value / --payload-enum-value
identify the specific aircraft/payload model in wpml:missionConfig. DJI's
enum table for Agras models isn't in the public docs either (only M30 = 67
was confirmed) -- these default to 0 and MUST be set correctly for your
actual drone model or Pilot 2 may reject the import outright.

SPRAYER CONTROL
----------------
Spray on/off is emitted as MAV_CMD_DO_SET_SERVO (command 183) toggling a
configurable servo/relay channel between a configurable "on" and "off" PWM
value. This is supported by both ArduPilot and PX4 and matches how a
servo-controlled sprayer valve is typically wired -- adjust
--sprayer-servo-channel / --sprayer-pwm-on / --sprayer-pwm-off to match
your actual hardware wiring.

USAGE
-----
python export_mission.py \
    --json flight_plan.json \
    --outdir ./output/missions \
    --format all \
    --sprayer-servo-channel 9 \
    --sprayer-pwm-on 1900 \
    --sprayer-pwm-off 1100
"""

import argparse
import csv
import json
import os


MAV_CMD_NAV_WAYPOINT = 16
MAV_CMD_NAV_RETURN_TO_LAUNCH = 20
MAV_CMD_NAV_TAKEOFF = 22
MAV_CMD_DO_SET_SERVO = 183
MAV_CMD_DO_SET_CAM_TRIGG_DIST = 206
FRAME_GLOBAL = 0
FRAME_GLOBAL_RELATIVE_ALT = 3


# ---------------------------------------------------------------------------
# Shared: expand a cycle's abstract actions (HOME/SPRAY_ON/SPRAY/SPRAY_OFF/
# TRANSIT/RTL) into a flat list of concrete MAVLink-style commands that
# every platform writer below consumes identically.
# ---------------------------------------------------------------------------

def expand_cycle_to_commands(cycle, servo_channel, pwm_on, pwm_off):
    """
    Returns a list of command dicts:
      {"cmd": "NAV_WAYPOINT", "lat":.., "lon":.., "alt":..}
      {"cmd": "DO_SET_SERVO", "param1": servo_channel, "param2": pwm_value}
      {"cmd": "RTL"}
    The first waypoint (HOME) is NOT included -- callers handle home
    position separately (it's a distinct concept in both output formats).
    """
    commands = []

    for wp in cycle["waypoints"][1:]:  # skip HOME, index 0
        action = wp["action"]

        if action == "RTL":
            commands.append({"cmd": "RTL"})
            continue

        commands.append({"cmd": "NAV_WAYPOINT", "lat": wp["lat"], "lon": wp["lon"], "alt": wp["alt"]})

        if action in ("SPRAY_ON", "SPRAY_ON_OFF"):
            commands.append({"cmd": "DO_SET_SERVO", "param1": servo_channel, "param2": pwm_on})
        if action in ("SPRAY_OFF", "SPRAY_ON_OFF"):
            commands.append({"cmd": "DO_SET_SERVO", "param1": servo_channel, "param2": pwm_off})

    return commands


# ---------------------------------------------------------------------------
# ArduPilot / Mission Planner -- QGC WPL 110 (.waypoints)
# ---------------------------------------------------------------------------

def write_ardupilot(cycle, commands, outpath, waypoint_hold_s=1.0,
                    takeoff_pitch_deg=15.0, emit_sprayer_servo=False,
                    cam_trigger_dist_m=0.0):
    """QGC WPL 120 waypoint file, in the layout verified against real hardware.

    Three things here differ from a naive reading of the QGC WPL spec, and all
    three are deliberate:

    - COLUMN ORDER IS LONGITUDE THEN LATITUDE. The format's own header calls
      these columns PARAM5/X/LONGITUDE and PARAM6/Y/LATITUDE, even though
      MAVLink's MISSION_ITEM puts latitude in param5 — the documentation and
      the wire protocol genuinely disagree. Flight-tested files from this
      project use lon-then-lat, and jobs/scouting_mission_generator's writer
      independently settled on the same order, so that is what is written
      here. Swapping it sends the aircraft somewhere else entirely.

    - TAKE-OFF CLIMBS TO THE MISSION'S ALTITUDE, NOT HOME'S. HOME sits at
      ground level (alt 0) in flight_plan.json, so using its altitude for the
      NAV_TAKEOFF item would command a take-off to 0 m.

    - EVERY WAYPOINT HOLDS. param1 of NAV_WAYPOINT is a hold time in seconds;
      a brief stop at each point is what a survey/scouting airframe wants, and
      it is harmless on a sprayer. Set --waypoint-hold-s 0 to fly through.

    Sprayer servo commands are opt-in (--emit-sprayer-servo): a plan flown on
    an aircraft with no sprayer should not carry DO_SET_SERVO items for a
    channel that isn't wired to anything.
    """
    home = cycle["waypoints"][0]
    # First waypoint carrying a real altitude — HOME's is ground level.
    flight_alt = next(
        (wp["alt"] for wp in cycle["waypoints"] if wp.get("alt")),
        home.get("alt", 0.0),
    )

    lines = ["QGC WPL 120"]
    seq = 0

    def add(current, frame, command, p1, p2, p3, p4, lon, lat, alt):
        # Sequence numbers advance only when a line is actually written, so a
        # skipped command (a suppressed servo item) cannot leave a gap — some
        # ground stations reject a file whose indices aren't contiguous.
        nonlocal seq
        lines.append("\t".join(str(v) for v in [
            seq, current, frame, command,
            float(p1), float(p2), float(p3), float(p4),
            float(lon), float(lat), float(alt), 1,
        ]))
        seq += 1

    add(1, FRAME_GLOBAL_RELATIVE_ALT, MAV_CMD_NAV_TAKEOFF,
        takeoff_pitch_deg, 0, 0, 0, home["lon"], home["lat"], flight_alt)

    # Trigger the camera every N metres for the rest of the mission. A spray
    # plan has no capture-distance of its own (only a scouting mission does),
    # so this is emitted only when asked for -- which is how a spray-shaped
    # plan gets flown as a survey on an aircraft carrying a camera.
    if cam_trigger_dist_m and cam_trigger_dist_m > 0:
        add(0, FRAME_GLOBAL_RELATIVE_ALT, MAV_CMD_DO_SET_CAM_TRIGG_DIST,
            cam_trigger_dist_m, 0, 0, 0, home["lon"], home["lat"], flight_alt)

    for cmd in commands:
        if cmd["cmd"] == "NAV_WAYPOINT":
            add(0, FRAME_GLOBAL_RELATIVE_ALT, MAV_CMD_NAV_WAYPOINT,
                waypoint_hold_s, 0, 0, 0, cmd["lon"], cmd["lat"], cmd["alt"])
        elif cmd["cmd"] == "DO_SET_SERVO":
            if emit_sprayer_servo:
                add(0, FRAME_GLOBAL_RELATIVE_ALT, MAV_CMD_DO_SET_SERVO,
                    cmd["param1"], cmd["param2"], 0, 0, 0, 0, 0)
        elif cmd["cmd"] == "RTL":
            add(0, FRAME_GLOBAL, MAV_CMD_NAV_RETURN_TO_LAUNCH, 0, 0, 0, 0, 0, 0, 0)

    with open(outpath, "w") as f:
        f.write("\n".join(lines) + "\n")


# ---------------------------------------------------------------------------
# PX4 / QGroundControl -- .plan (JSON)
# ---------------------------------------------------------------------------

def write_px4(cycle, commands, outpath, cruise_speed_mps, hover_speed_mps):
    home = cycle["waypoints"][0]

    items = []
    do_jump_id = 1
    for cmd in commands:
        if cmd["cmd"] == "NAV_WAYPOINT":
            items.append({
                "AMSLAltAboveTerrain": None,
                "Altitude": cmd["alt"],
                "AltitudeMode": 1,
                "autoContinue": True,
                "command": MAV_CMD_NAV_WAYPOINT,
                "doJumpId": do_jump_id,
                "frame": 3,
                "params": [0, 0, 0, None, cmd["lat"], cmd["lon"], cmd["alt"]],
                "type": "SimpleItem",
            })
        elif cmd["cmd"] == "DO_SET_SERVO":
            items.append({
                "AMSLAltAboveTerrain": None,
                "Altitude": 0,
                "AltitudeMode": 1,
                "autoContinue": True,
                "command": MAV_CMD_DO_SET_SERVO,
                "doJumpId": do_jump_id,
                "frame": 3,
                "params": [cmd["param1"], cmd["param2"], 0, 0, 0, 0, 0],
                "type": "SimpleItem",
            })
        elif cmd["cmd"] == "RTL":
            items.append({
                "AMSLAltAboveTerrain": None,
                "Altitude": 0,
                "AltitudeMode": 1,
                "autoContinue": True,
                "command": MAV_CMD_NAV_RETURN_TO_LAUNCH,
                "doJumpId": do_jump_id,
                "frame": 3,
                "params": [0, 0, 0, 0, 0, 0, 0],
                "type": "SimpleItem",
            })
        do_jump_id += 1

    plan = {
        "fileType": "Plan",
        "geoFence": {"circles": [], "polygons": [], "version": 2},
        "groundStation": "QGroundControl",
        "mission": {
            "cruiseSpeed": cruise_speed_mps,
            "firmwareType": 12,  # PX4
            "globalPlanAltitudeMode": 1,
            "hoverSpeed": hover_speed_mps,
            "items": items,
            "plannedHomePosition": [home["lat"], home["lon"], 0],
            "vehicleType": 2,  # multirotor
            "version": 2,
        },
        "rallyPoints": {"points": [], "version": 2},
        "version": 1,
    }

    with open(outpath, "w") as f:
        json.dump(plan, f, indent=2)


# ---------------------------------------------------------------------------
# Generic debug CSV -- not tied to any specific consumer app's format
# ---------------------------------------------------------------------------

def write_generic_csv(cycle, outpath):
    with open(outpath, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["seq", "lat", "lon", "altitude_ft", "action"])
        for wp in cycle["waypoints"]:
            writer.writerow([wp["seq"], wp["lat"], wp["lon"], wp["alt"], wp["action"]])


# ---------------------------------------------------------------------------
# DJI WPML (.kmz)
# ---------------------------------------------------------------------------

FT_TO_M = 0.3048

# UNVERIFIED PLACEHOLDER -- see module docstring. Replace via
# --spray-action-tag / --spray-param-tag once confirmed against a real
# DJI Agras / Pilot 2 export.
DEFAULT_SPRAY_ACTION_TAG = "sprayerEnable"
DEFAULT_SPRAY_PARAM_TAG = "sprayerEnable"


def _group_commands_into_dji_waypoints(commands):
    """
    Groups the flat command list into per-waypoint records, attaching any
    DO_SET_SERVO commands that immediately follow a NAV_WAYPOINT to that
    waypoint (matching how expand_cycle_to_commands emits them). RTL is
    dropped here -- it's expressed via wpml:finishAction=goHome instead of
    a placemark, per DJI's documented finishAction options.
    """
    waypoints = []
    for cmd in commands:
        if cmd["cmd"] == "NAV_WAYPOINT":
            waypoints.append({
                "lat": cmd["lat"], "lon": cmd["lon"],
                "alt_m": cmd["alt"] * FT_TO_M,
                "servo_actions": [],
            })
        elif cmd["cmd"] == "DO_SET_SERVO" and waypoints:
            waypoints[-1]["servo_actions"].append(cmd)
        # RTL: no placemark; handled by finishAction below
    return waypoints


def _build_placemark_xml(idx, wp, speed_mps, action_id_counter, spray_action_tag, spray_param_tag):
    """Returns (placemark_xml_string, next_action_id)."""
    action_id = action_id_counter

    action_group_xml = ""
    if wp["servo_actions"]:
        actions_xml = ""
        for servo_cmd in wp["servo_actions"]:
            is_on = servo_cmd["param2"] >= 1500  # PWM midpoint heuristic: >=1500 = "on" side
            spray_value = 1 if is_on else 0
            actions_xml += f"""
        <wpml:action>
          <wpml:actionId>{action_id}</wpml:actionId>
          <!-- UNVERIFIED: placeholder tag, confirm against a real Agras export -->
          <wpml:actionActuatorFunc>{spray_action_tag}</wpml:actionActuatorFunc>
          <wpml:actionActuatorFuncParam>
            <wpml:{spray_param_tag}>{spray_value}</wpml:{spray_param_tag}>
          </wpml:actionActuatorFuncParam>
        </wpml:action>"""
            action_id += 1

        action_group_xml = f"""
        <wpml:actionGroup>
          <wpml:actionGroupId>{idx}</wpml:actionGroupId>
          <wpml:actionGroupStartIndex>{idx}</wpml:actionGroupStartIndex>
          <wpml:actionGroupEndIndex>{idx}</wpml:actionGroupEndIndex>
          <wpml:actionGroupMode>sequence</wpml:actionGroupMode>
          <wpml:actionTrigger>
            <wpml:actionTriggerType>reachPoint</wpml:actionTriggerType>
          </wpml:actionTrigger>{actions_xml}
        </wpml:actionGroup>"""

    placemark = f"""      <Placemark>
        <Point>
          <coordinates>{wp['lon']:.8f},{wp['lat']:.8f}</coordinates>
        </Point>
        <wpml:index>{idx}</wpml:index>
        <wpml:executeHeight>{wp['alt_m']:.2f}</wpml:executeHeight>
        <wpml:waypointSpeed>{speed_mps:.2f}</wpml:waypointSpeed>
        <wpml:waypointHeadingParam>
          <wpml:waypointHeadingMode>followWayline</wpml:waypointHeadingMode>
        </wpml:waypointHeadingParam>
        <wpml:waypointTurnParam>
          <wpml:waypointTurnMode>toPointAndStopWithDiscontinuityCurvature</wpml:waypointTurnMode>
        </wpml:waypointTurnParam>
        <wpml:useStraightLine>1</wpml:useStraightLine>{action_group_xml}
      </Placemark>"""

    return placemark, action_id


def _build_wpml_document(cycle, commands, speed_mps, drone_enum_value, drone_sub_enum_value,
                          payload_enum_value, payload_position_index,
                          spray_action_tag, spray_param_tag, template_id=0, wayline_id=0):
    """
    Builds the XML body shared by template.kml and waylines.wpml -- per
    DJI's docs the two files share the missionConfig/Folder/Placemark
    schema (template.kml = "business attributes", waylines.wpml =
    "execution details"); this generates a faithful mission definition
    used for both.
    """
    dji_waypoints = _group_commands_into_dji_waypoints(commands)

    placemarks_xml = ""
    action_id = 1
    for idx, wp in enumerate(dji_waypoints):
        placemark_xml, action_id = _build_placemark_xml(
            idx, wp, speed_mps, action_id, spray_action_tag, spray_param_tag
        )
        placemarks_xml += "\n" + placemark_xml

    doc = f"""<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:wpml="http://www.dji.com/wpmz/1.0.2">
  <Document>
    <wpml:missionConfig>
      <wpml:flyToWaylineMode>safely</wpml:flyToWaylineMode>
      <wpml:finishAction>goHome</wpml:finishAction>
      <wpml:exitOnRCLost>executeLostAction</wpml:exitOnRCLost>
      <wpml:executeRCLostAction>hover</wpml:executeRCLostAction>
      <wpml:takeOffSecurityHeight>20</wpml:takeOffSecurityHeight>
      <wpml:globalTransitionalSpeed>{speed_mps:.2f}</wpml:globalTransitionalSpeed>
      <wpml:droneInfo>
        <!-- UNVERIFIED: confirm droneEnumValue/droneSubEnumValue for your actual Agras model -->
        <wpml:droneEnumValue>{drone_enum_value}</wpml:droneEnumValue>
        <wpml:droneSubEnumValue>{drone_sub_enum_value}</wpml:droneSubEnumValue>
      </wpml:droneInfo>
      <wpml:payloadInfo>
        <!-- UNVERIFIED: confirm payloadEnumValue for your actual sprayer payload -->
        <wpml:payloadEnumValue>{payload_enum_value}</wpml:payloadEnumValue>
        <wpml:payloadPositionIndex>{payload_position_index}</wpml:payloadPositionIndex>
      </wpml:payloadInfo>
    </wpml:missionConfig>
    <Folder>
      <wpml:templateId>{template_id}</wpml:templateId>
      <wpml:executeHeightMode>relativeToStartPoint</wpml:executeHeightMode>
      <wpml:waylineId>{wayline_id}</wpml:waylineId>
      <wpml:autoFlightSpeed>{speed_mps:.2f}</wpml:autoFlightSpeed>
{placemarks_xml}
    </Folder>
  </Document>
</kml>
"""
    return doc


def export_dji_wpml(cycle, commands, outpath, speed_mps,
                     drone_enum_value, drone_sub_enum_value, payload_enum_value,
                     payload_position_index, spray_action_tag, spray_param_tag):
    """
    Writes a .kmz containing wpmz/template.kml, wpmz/waylines.wpml, and an
    empty wpmz/res/ folder, per DJI's documented WPML file structure.

    NOTE: see module docstring -- the spray action tag/params are
    unverified placeholders, and the drone/payload enum values default to
    0 and must be set for your actual aircraft model.
    """
    import zipfile

    xml_doc = _build_wpml_document(
        cycle, commands, speed_mps,
        drone_enum_value, drone_sub_enum_value, payload_enum_value, payload_position_index,
        spray_action_tag, spray_param_tag,
    )

    with zipfile.ZipFile(outpath, "w", zipfile.ZIP_DEFLATED) as kmz:
        kmz.writestr("wpmz/template.kml", xml_doc)
        kmz.writestr("wpmz/waylines.wpml", xml_doc)
        kmz.writestr("wpmz/res/.gitkeep", "")  # DJI's spec includes a res/ folder even if unused here


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Export flight_plan.json into platform-specific mission files")
    parser.add_argument("--json", required=True, help="Path to flight_plan.json")
    parser.add_argument("--outdir", required=True, help="Output directory")
    parser.add_argument("--format", choices=["ardupilot", "px4", "generic_csv", "dji", "all"], default="all")

    parser.add_argument("--sprayer-servo-channel", type=int, default=9,
                         help="Servo/relay channel used for sprayer on/off (default 9)")
    parser.add_argument("--sprayer-pwm-on", type=int, default=1900, help="PWM value for sprayer ON (default 1900)")
    parser.add_argument("--sprayer-pwm-off", type=int, default=1100, help="PWM value for sprayer OFF (default 1100)")

    parser.add_argument("--waypoint-hold-s", type=float, default=1.0,
                        help="ArduPilot: seconds to hold at each waypoint (NAV_WAYPOINT param1). "
                             "0 flies through without stopping (default 1.0)")
    parser.add_argument("--cam-trigger-dist-m", type=float, default=0.0,
                        help="ArduPilot: trigger the camera every N metres "
                             "(MAV_CMD_DO_SET_CAM_TRIGG_DIST). 0 disables it (default 0)")
    parser.add_argument("--takeoff-pitch", type=float, default=15.0,
                        help="ArduPilot: NAV_TAKEOFF minimum pitch in degrees (default 15.0)")
    parser.add_argument("--emit-sprayer-servo", action="store_true",
                        help="ArduPilot: emit DO_SET_SERVO sprayer items. Off by default - an "
                             "airframe with no sprayer should not carry them")
    parser.add_argument("--cruise-speed-mps", type=float, default=None,
                         help="Cruise speed in m/s (default: derived from flight_plan.json meta speed_mph)")
    parser.add_argument("--hover-speed-mps", type=float, default=5.0, help="PX4 hover speed in m/s (default 5.0)")

    parser.add_argument("--drone-enum-value", type=int, default=0,
                         help="UNVERIFIED placeholder -- DJI drone model enum for wpml:missionConfig (default 0, "
                              "must be set correctly for your Agras model, see module docstring)")
    parser.add_argument("--drone-sub-enum-value", type=int, default=0, help="DJI drone sub-model enum (default 0)")
    parser.add_argument("--payload-enum-value", type=int, default=0,
                         help="UNVERIFIED placeholder -- DJI payload/sprayer enum (default 0)")
    parser.add_argument("--payload-position-index", type=int, default=0, help="DJI payload mount position (default 0)")
    parser.add_argument("--spray-action-tag", type=str, default=DEFAULT_SPRAY_ACTION_TAG,
                         help=f"UNVERIFIED placeholder -- actionActuatorFunc tag for spray on/off "
                              f"(default '{DEFAULT_SPRAY_ACTION_TAG}')")
    parser.add_argument("--spray-param-tag", type=str, default=DEFAULT_SPRAY_PARAM_TAG,
                         help=f"UNVERIFIED placeholder -- param tag name inside the spray action "
                              f"(default '{DEFAULT_SPRAY_PARAM_TAG}')")

    args = parser.parse_args()
    os.makedirs(args.outdir, exist_ok=True)

    with open(args.json, "r") as f:
        plan_data = json.load(f)

    meta = plan_data.get("meta", {})
    cruise_speed_mps = args.cruise_speed_mps
    if cruise_speed_mps is None:
        speed_mph = meta.get("speed_mph", 15.0)
        cruise_speed_mps = speed_mph * 0.44704

    formats = ["ardupilot", "px4", "generic_csv", "dji"] if args.format == "all" else [args.format]

    for fmt in formats:
        fmt_dir = os.path.join(args.outdir, fmt)
        os.makedirs(fmt_dir, exist_ok=True)

    if "dji" in formats and (args.drone_enum_value == 0 or args.payload_enum_value == 0):
        print(
            "WARNING: --drone-enum-value / --payload-enum-value are at their placeholder default (0). "
            "DJI Pilot 2 will likely reject the .kmz import until these are set to your actual aircraft "
            "model's real enum values. Same caveat applies to --spray-action-tag / --spray-param-tag -- "
            "see module docstring."
        )

    for cycle in plan_data["cycles"]:
        cycle_id = cycle["cycle_id"]
        commands = expand_cycle_to_commands(
            cycle, args.sprayer_servo_channel, args.sprayer_pwm_on, args.sprayer_pwm_off
        )

        if "ardupilot" in formats:
            path = os.path.join(args.outdir, "ardupilot", f"flight_plan_cycle{cycle_id}.waypoints")
            write_ardupilot(cycle, commands, path,
                            waypoint_hold_s=args.waypoint_hold_s,
                            takeoff_pitch_deg=args.takeoff_pitch,
                            emit_sprayer_servo=args.emit_sprayer_servo,
                            cam_trigger_dist_m=args.cam_trigger_dist_m)
            print(f"Wrote {path}")

        if "px4" in formats:
            path = os.path.join(args.outdir, "px4", f"flight_plan_cycle{cycle_id}.plan")
            write_px4(cycle, commands, path, cruise_speed_mps, args.hover_speed_mps)
            print(f"Wrote {path}")

        if "generic_csv" in formats:
            path = os.path.join(args.outdir, "generic_csv", f"flight_plan_cycle{cycle_id}.csv")
            write_generic_csv(cycle, path)
            print(f"Wrote {path}")

        if "dji" in formats:
            path = os.path.join(args.outdir, "dji", f"flight_plan_cycle{cycle_id}.kmz")
            export_dji_wpml(
                cycle, commands, path, cruise_speed_mps,
                args.drone_enum_value, args.drone_sub_enum_value,
                args.payload_enum_value, args.payload_position_index,
                args.spray_action_tag, args.spray_param_tag,
            )
            print(f"Wrote {path}")

    print(f"\nExported {len(plan_data['cycles'])} charge cycle(s) x {len(formats)} format(s)")


if __name__ == "__main__":
    main()